### ISSUE TITLE
Fish 2.3.0-1 update breaks everything

### ISSUE THREAD

**Issue by Poorchop** [oh-my-fish/oh-my-fish#340]
OS: Fedora 23

I ran an update this morning and fish 2.3.0-1 was included. Immediately after the update finished, I got some extremely long traceback regarding how `string` was an unknown command. I closed the ssh session and the traceback disappeared, but the prompt colors were all wrong (using theme fox). I tried installing a few other themes and they all seemed to be broken as well, especially in tmux sessions. I tried to reinstall omf but the problem persisted. I ran `omf doctor` many times along the way but I had no issues apart from having to remove a fish config file since it was overriding my themes, an error that I encountered after installing several different themes to see if they were all broken.

Eventually I removed omf, deleted all fish and omf folders in ~/.config and ~/.local/share, and I reinstalled omf. At this point, I couldn't even start a tmux session and I'd just get the error about not being able to use /dev/tty when I tried. I reinstalled the fox theme, encountered the same error, then switched back to the default theme and got an error about `git_is_repo` not being a recognized command.

I also reinstalled fish twice while trying to figure out what was going on, but it didn't change anything. Now I can't even launch a tmux session at all while omf is installed, so I have just removed it altogether for the time being and everything is otherwise working properly. Unfortunately, I didn't save any tracebacks, but they only pertained to `string` and `git_is_repo` not being recognized commands. Both of these errors disappeared either after restarting the ssh session or after reinstalling omf.

**Comment by Poorchop** [comment]
Just as an addendum:

I ran `dnf downgrade fish`, which reverted to fish-2.2.0-3. Themes are working properly and I can finally start a tmux session. However, plugins apparently aren't being loaded. I can install and switch themes, but I installed both [plugin-tmux](https://github.com/oh-my-fish/plugin-tmux) and [plug-extract](https://github.com/oh-my-fish/plugin-extract) without any luck. `extract` isn't being recognized as a command. I hope that I didn't break anything by deleting the fish and omf folders in ~/.config and ~/.local/share.

**Comment by derekstavis** [comment]
Can you please paste the contents of `echo $fish_function_path`?

**Comment by Poorchop** [comment]
`/home/poorchop/.config/fish/functions /home/poorchop/.local/share/omf/pkg/omf/functions/compat /home/poorchop/.local/share/omf/pkg/omf/functions/core /home/poorchop/.local/share/omf/pkg/omf/functions/packages /home/poorchop/.local/share/omf/pkg/omf/functions/themes /home/poorchop/.local/share/omf/pkg/omf/functions/bundle /home/poorchop/.local/share/omf/pkg/omf/functions/util /home/poorchop/.local/share/omf/pkg/omf/functions/repo /home/poorchop/.local/share/omf/pkg/omf/functions/cli /home/poorchop/.local/share/omf/pkg/omf/functions/search /home/poorchop/.local/share/omf/pkg/fish-spec/functions /home/poorchop/.local/share/omf/pkg/omf/functions /home/poorchop/.local/share/omf/lib /home/poorchop/.local/share/omf/lib/git /home/poorchop/.local/share/omf/themes/default /etc/fish/functions /usr/share/fish/vendor_functions.d /usr/share/fish/functions`

I also removed oh-my-fish and updated to the latest fish again, but I still ran into the fish prompt error with `string` not being a recognized command. Apparently that error has nothing to do with oh-my-fish, but everything else still stands.

**Comment by derekstavis** [comment]
It looks to me that everything is correct in what concerns to Oh My Fish paths. The default theme also should work correctly. What you need to make sure is if you are not overriding anything on functions defined inside `/home/poorchop/.config/fish/functions`.

**Comment by Poorchop** [comment]
I don't think I'm overriding anything. I never touched anything apart from updating fish and installing a few themes and two plugins: tmux and extract. After uninstalling oh-my-fish, I subsequently deleted ~/.config/fish, ~/.config/omf, and ~/.local/share/fish. I also cleared my fish history with `history --clear`, but that's it.

It looks like ~/.config/fish/functions/fish_prompt.fish is symlinked from ~/.local/share/omf/themes/fox/fish_prompt.fish and I haven't modified it. I don't have a problem with the latest fish being broken since I can just downgrade, but I don't understand what I did to break the loading of plugins on fish 2.2.0-3.

**Comment by derekstavis** [comment]
Please remove the `~/.config/fish/functions/fish_prompt.fish` symlink. It should fix the broken prompt.

**Comment by Poorchop** [comment]
I removed the symlink but themes are still broken in the latest fish. I still can't start a tmux session in fish 2.3.0-1 and I get the following error: `open terminal failed: can't use /dev/tty`.

It looks like 2.3.0 is just broken in general but it seems to have ruined everything, even when I downgrade to 2.2.0. Plugins aren't working now no matter what.

**Comment by coderstephen** [comment]
That's pretty odd... I wonder if there's any open issues on Fish about breaking either the history files or state files.

Something strange must be happening here, since I am using Fish 2.3.0 + OMF locally now with no issues.

**Comment by Poorchop** [comment]
I tried a different fish plugin manager and it loaded both the extract and tmux plugins without any issues. I haven't tried the themes yet but it seems pretty clear that 2.3.0 broke something in oh-my-fish, at least on my end. There's definitely something fishy about the update itself since it's spitting that error message even when I'm not using oh-my-fish. I haven't been able to replicate the `git_is_repo` error yet however.

I don't see any issues in their repo that specifically outline my problems, but there is [this](https://github.com/fish-shell/fish-shell/issues/3106):

>It seems 2.3.0 isn't perfect and had some small issues.

I did some quick browsing but I don't see what those issues are exactly. Perhaps this should be closed since the only factor that changed was updating fish, and no other omf users are having issues, so it's probably just upstream.

**Comment by coderstephen** [comment]
`open terminal failed: can't use /dev/tty` definitely seems like a Fish issue, and that error may have an effect on OMF somehow, though it isn't obvious to me what that might be.

If you are connecting over SSH, [this open issue](https://github.com/fish-shell/fish-shell/issues/2980) seems like a strong contender for a source of your problems. On install, OMF reloads Fish by replacing itself with a new Fish process. It is very possible that this bug causes the new Fish process to have the wrong TTY modes set, and breaks everything.

**Comment by Poorchop** [comment]
You're absolutely right, my issues were mainly from connecting over SSH. I finally tested locally however and it still turns out that the update is breaking theme colors, at least in the fox theme. I don't think there's anything to be done here however, at least not until they release 2.3.1. The issue you linked looks like the major blocking issue, so hopefully these problems are all upstream and will be addressed soon enough.

**Comment by derekstavis** [comment]
Hey @Poorchop, sorry for the delay! We've done a bunch of fixes back then, would you mind reporting how it is going for you?

**Comment by onbjerg** [comment]
Can't even install on fish 2.3.1.

```
onbjerg@hari ~> git --version
git version 2.9.1
onbjerg@hari ~> fish --version
fish, version 2.3.1
onbjerg@hari ~> curl -L https://github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | fish
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0source: Error encountered while sourcing file '/Users/onbjerg/.local/share/omf/init.fish':
source: No such file or directory
100   140  100   140    0     0    233      0 --:--:-- --:--:-- --:--:--   232
100  4693  100  4693    0     0   6156      0 --:--:-- --:--:-- --:--:--  6156
Installing Oh My Fish to /Users/onbjerg/.local/share/omf...
Cloning master from https://github.com/oh-my-fish/oh-my-fish.git...
Existent config.fish found at /Users/onbjerg/.config/fish
↳ Moving to /Users/onbjerg/.config/fish/config.1470592526.copy
Adding startup code to fish config file...
Building Oh My Fish configuration...
Illegal command name '{$OMF_CONFIG,$OMF_PATH}/pkg/*/key_bindings.fish'
~/.local/share/omf/init.fish (line 33):                       {$OMF_CONFIG,$OMF_PATH}/pkg/*/key_bindings.fish \
                                                              ^
from sourcing file ~/.local/share/omf/init.fish
        called on line 10 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
        called during startup

source: Error while reading file '/Users/onbjerg/.local/share/omf/init.fish'
fish: Unknown command 'omf install'
fish: omf install
      ^
Oh My Fish installation failed.

If you think that it's a bug, please open an
issue with the complete installation log here:

http://github.com/oh-my-fish/oh-my-fish/issues
```
