### ISSUE TITLE
emacs package not being loaded

### ISSUE THREAD

**Issue by CeleritasCelery** [oh-my-fish/oh-my-fish#561]
Using:
Suse Linux
Fish 2.6.0
Oh My Fish 5-31-ga89771c
git 2.8.4

I can install themes just fine, but I am having trouble having the package functions loaded. For example I install the emacs package with `omf install emacs` and I can see it with `omf list` but none of the function are available, even after `omf reload`. If I manually source the function I get them, but other then that they are never loaded. How do I debug what is going wrong?

**Comment by oranja** [comment]
What's going on is that this plugin hasn't been updated in a long while.
Unless @bpinto hopefully reappears out of the blue, it might be time to take over the repository or fork and update the official package repository.

This PR should fix the plugin to work with current versions of OMF:
https://github.com/oh-my-fish/plugin-emacs/pull/3

**Comment by tasmo** [comment]
I added the repo locally with:

```shell
# omf repositories add <url> [<branch>]
omf repositories add https://github.com/bobthecow/plugin-emacs fishier
omf install https://github.com/bobthecow/plugin-emacs
```

After `omf reload` it works.

**Comment by bpinto** [comment]
I have merged the PR. Has it been fixed now?

**Comment by CeleritasCelery** [comment]
It is still not working by default. I even tried to destroy and reinstall omf. However @tasmo's hack works.

**Comment by tasmo** [comment]
@bpinto It works for me now taking the master branch from [oh-my-fish/plugin-emacs](https://github.com/oh-my-fish/plugin-emacs). Thank you!

**Comment by sagebind** [comment]
It looks like the reason it isn't getting the changes is that the `emacs` package in the main repository is pointing to a different repository:

```
-> omf describe emacs
Package: emacs
Description: Emacs plugin for the Wahoo Fish Shell Framework
Repository: https://github.com/cap10morgan/wa-emacs
Maintainer:
```

**Comment by sagebind** [comment]
@CeleritasCelery @tasmo OK, try it now:

```
$ omf repo rm https://github.com/bobthecow/plugin-emacs fishier
$ omf remove emacs
$ omf install emacs
```
